/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-11 05:15:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexlog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/resources/static/css/common.css", Long.valueOf(1691327317800L));
    _jspx_dependants.put("jar:file:/C:/workspace_team/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PJ_TEAM01/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
    _jspx_dependants.put("/resources/static/css/footer.css", Long.valueOf(1691327317808L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1692698660757L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1692698618642L));
    _jspx_dependants.put("jar:file:/C:/workspace_team/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PJ_TEAM01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/resources/static/css/header.css", Long.valueOf(1691327317815L));
    _jspx_dependants.put("/resources/static/css/Main_Page_log.css", Long.valueOf(1693895250440L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\" />\r\n");
      out.write("	<style>\r\n");
      out.write("		");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'SDSamliphopangche_Basic';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/SDSamliphopangche_Basic.woff') format('woff');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 2px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: 'SDSamliphopangche_Basic';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    margin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.mobilemenu>.material-symbols-outlined{ \r\n");
      out.write("    font-variation-settings:\r\n");
      out.write("    'FILL' 0,\r\n");
      out.write("    'wght' 400,\r\n");
      out.write("    'GRAD' 0,\r\n");
      out.write("    'opsz' 48}");
      out.write("\r\n");
      out.write("		");
      out.write("/* header */\r\n");
      out.write(".wrapper>header {\r\n");
      out.write("    height:130px;\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* íí¤ë ë´ ë¡ê³ , ê²ìì°½, íµë©ë´ ì ì²´ */\r\n");
      out.write(".wrapper>header>.top-header{\r\n");
      out.write("    height: 110px;\r\n");
      out.write("    /* border: 1px solid green; */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* íí¤ë ë´ ë¡ê³  */\r\n");
      out.write(".wrapper>header>.top-header>.logo{\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* íí¤ë ë´ ê²ìì°½ */\r\n");
      out.write(".wrapper>header>.top-header>form .search_box{\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    border: 3px solid rgb(92, 115, 6);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("    line-height: 35px;\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>form .search_box>div{\r\n");
      out.write("    /* border: 1px solid rosybrown; */\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 35px;\r\n");
      out.write("    margin-top: -1px;\r\n");
      out.write("    margin-left: -10px;\r\n");
      out.write("    border-right: 3px solid rgb(92, 115, 6);\r\n");
      out.write("    background-color: rgba(92, 115, 6, 0.43);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>form .search_box>input {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    width: 340px;\r\n");
      out.write("    border: 1px;\r\n");
      out.write("    outline: 1px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -1px;\r\n");
      out.write("    left: 115px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-family: 'NanumSquareBold';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>form .search_box>img {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    left: 92%;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* í¤ë ë´ íµë©ë´ */\r\n");
      out.write(".wrapper>header>.top-header>ul {\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: right;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>ul>li {\r\n");
      out.write("    /* border: 1px solid gray; */\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>ul>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.top-header>ul>li>a>img{\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -2.5px;\r\n");
      out.write("    left: -5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* navë¶ë¶ STYLE */\r\n");
      out.write(".wrapper>nav>.navi{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ì¼ìª½ nav one-depth */\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    /* transition: 1s; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ì¼ìª½ nav two-depth */\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>.two--depth {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    display: none;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>.two--depth>li {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>.two--depth>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>a:hover {\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li:hover .two--depth {\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_left>.one--depth>li>.two--depth>li>a:hover {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    transition: 0.7s;\r\n");
      out.write("    color: rgb(192, 57, 43);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ì¤ë¥¸ìª½ nav one-depth */\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ì¤ë¥¸ìª½ nav two-depth */\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>.two--depth {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>.two--depth>li {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>.two--depth>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>a:hover {\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li:hover .two--depth {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    right: -12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.navi>.Menu_right>.one--depth>li>.two--depth>li>a:hover {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    transition: 0.7s;\r\n");
      out.write("    color: rgb(192, 57, 43);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header_line */\r\n");
      out.write(".wrapper>.header_line {\r\n");
      out.write("    display: block;\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 5px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>#footer_logo{\r\n");
      out.write("    border: 1px solid;\r\n");
      out.write("    opacity: 0.6;\r\n");
      out.write("    margin-bottom: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header{\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write(".logheader_line{\r\n");
      out.write("    display: block;\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* login header */\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header>a>.logo{\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header>ul{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header>ul>li{\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header>ul>li>a{\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    position: relative;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>header>.log-header>ul>li>a>img{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    right: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>nav>.mobilemenu{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("/* Section1 */\r\n");
      out.write("\r\n");
      out.write(".section1 {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside {\r\n");
      out.write("    color: rgb(192, 57, 43);\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    width: 900px;\r\n");
      out.write("    font-size: 2.5rem;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1 {\r\n");
      out.write("    width: 830px;\r\n");
      out.write("    height: 280px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    border: 1px solid gray;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1>.swiper-wrapper{\r\n");
      out.write("    width: 830px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1>.swiper-wrapper>.swiper-slide{\r\n");
      out.write("    width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1>.swiper-wrapper>.swiper-slide>a{\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("    height: 220px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    transition: transform 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1>.swiper-wrapper>.swiper-slide>a:hover{\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1 > aside > .d1 > .swiper-wrapper>.swiper-slide> a:active,\r\n");
      out.write(".section1 > aside > .d1 > .swiper-wrapper>.swiper-slide> a:focus {\r\n");
      out.write("  transform: scale(1); \r\n");
      out.write("  transition: transform 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>aside>.d1>.swiper-wrapper>.swiper-slide>a>img{\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    height: 220px;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article {\r\n");
      out.write("    border: 1px solid lightgray;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 320px;\r\n");
      out.write("    height: 250px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    font-size: 1.3rem;\r\n");
      out.write("    padding-top: 40px;\r\n");
      out.write("    margin-top: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article>div {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article>div>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article>div>a>img {\r\n");
      out.write("    width: 60px;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article>div>span {\r\n");
      out.write("    display: inline;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    line-height: 70px;\r\n");
      out.write("    margin-left: 80px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section1>article>h4 {\r\n");
      out.write("    display: block;\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    margin: 15px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".section1>article>form>button {\r\n");
      out.write("    width: 70px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    background-color: rgb(192, 57, 43);\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Section2 */\r\n");
      out.write("\r\n");
      out.write(".section2 {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    margin: 20px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside:nth-child(1) {\r\n");
      out.write("    color: rgb(192, 57, 43);\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    font-size: 2.3rem;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 450px;\r\n");
      out.write("    border: 1px solid lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside:nth-child(1)>a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    color: rgb(92, 115, 6);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside:nth-child(1)>span {\r\n");
      out.write("    font-size: 1.1rem;\r\n");
      out.write("    color: black;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: start;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>a img {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside:nth-child(2) {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper>a {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -30px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>.top10 {\r\n");
      out.write("    background-color: rgba(92, 115, 6, 0.43);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: rgb(92, 115, 6);\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>.top10>img {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -20px;\r\n");
      out.write("    left: 210px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("    opacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>.top10>span:nth-child(1) {\r\n");
      out.write("    font-size: 1.4rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>.top10>span:nth-child(2) {\r\n");
      out.write("    font-size: 1.7rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>aside>table {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper>div{\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: right;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper>div>a{\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    background-color: rgb(192, 57, 43);\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 70px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th,\r\n");
      out.write("td {\r\n");
      out.write("    padding: 2px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    border-bottom: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("    background-color: #f2f2f2;\r\n");
      out.write("    width: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>article {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    margin: 20px 10px;\r\n");
      out.write("    color: rgb(192, 57, 43);\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    font-size: 2.3rem;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border: 1px solid lightgray;\r\n");
      out.write("    width: 450px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>article>div {\r\n");
      out.write("    margin-top: 70px;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>article>div>a {\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    background-color: rgba(92, 115, 6, 0.43);\r\n");
      out.write("    color: rgb(92, 115, 6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section2>article>span {\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-size: 1.8rem;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("		");
      out.write("/* footer */\r\n");
      out.write("\r\n");
      out.write("/* footer line */\r\n");
      out.write(".wrapper>footer>.footer_line {\r\n");
      out.write("    display: block;\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 5px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* footer */\r\n");
      out.write(".wrapper>footer>div>.footer_menu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    /* border: 1px solid; */\r\n");
      out.write("    height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>div>.footer_menu>li{\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("    width: 140px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>div>.footer_menu>li>a{\r\n");
      out.write("    font-family: 'NanumSquareAceb'; \r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>.Site_info{\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>.Site_info>#footer_logo{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -50px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    height: 110px;\r\n");
      out.write("    opacity: 0.3;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>.Site_info>span{\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 2px 40px 2px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper>footer>.Site_info>.Sitename{\r\n");
      out.write("    font-family: 'NanumSquareAceb'; \r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("}");
      out.write("		\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("        <!-- 메인 -->\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"top-header\">\r\n");
      out.write("                <a href=");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("><img class=\"logo\" src=\"resources/static/img/로고.png\" alt=\"\"></a>\r\n");
      out.write("                <form action=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" method=\"get\">\r\n");
      out.write("                <div class=\"search_box\">\r\n");
      out.write("                    <div class=\"search_btn\" id=\"searchButton\">SEARCH</div>\r\n");
      out.write("                    <input id=\"searchInput\" type=\"text\" name=\"searchText\" placeholder=\"듣고 싶은 노래를 검색하세요!\" >\r\n");
      out.write("                    <img id=\"searchbtn\" src=\"resources/static/img/search.png\" alt=\"\" onclick=\"window.location.href='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"\" style=\"color:rgb(92, 115, 6); font-family: 'SDSamliphopangche_Basic'; font-size: 19px;\"><img\r\n");
      out.write("                                src=\"resources/static/img/add.png\" alt=\"\"> 멤버십가입</a></li>\r\n");
      out.write("                    <li><a href=\"\"><img src=\"resources/static/img/english.png\" alt=\"\">ENGLISH</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <div class=\"mobilemenu\">\r\n");
      out.write("                <span href=\"\" class=\"material-symbols-outlined\">menu\r\n");
      out.write("                    <ul class=\"wa\">\r\n");
      out.write("                        <li><a href=\"\">수박차트</a></li>\r\n");
      out.write("                        <li><a href=\"\">수박DJ</a></li>\r\n");
      out.write("                        <li><a href=\"\">수박TV</a></li>\r\n");
      out.write("                        <li><a href=\"\">수박매거진</a></li>                        \r\n");
      out.write("                        <li><a href=\"./QnA_Page.html\">공지사항</a></li>                        \r\n");
      out.write("                        <li><a href=\"\">마이페이지</a></li>                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </span>    \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navi\">\r\n");
      out.write("                <div class=\"Menu_left\">\r\n");
      out.write("                    <ul class=\"one--depth\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">수박차트</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=\"\">국내TOP100</a></li>\r\n");
      out.write("                                <li><a href=\"\">해외TOP100</a></li>\r\n");
      out.write("                                <li><a href=\"\">최신음악</a></li>\r\n");
      out.write("                                <li><a href=\"\">장르음악</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">수박DJ</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=\"\">#투데이</a></li>\r\n");
      out.write("                                <li><a href=\"\">테마장르</a></li>\r\n");
      out.write("                                <li><a href=\"\">인기선곡</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">수박TV</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=\"\">뮤직비디오</a></li>\r\n");
      out.write("                                <li><a href=\"\">수박방송</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">수박매거진</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=\"./magazine.html\">오늘의매거진</a></li>\r\n");
      out.write("                                <li><a href=\"\">완결매거진</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"Menu_right\">\r\n");
      out.write("                    <ul class=\"one--depth\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">공지사항</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"\">QnA</a></li>\r\n");
      out.write("                                <li><a href=\"\">자주하는질문</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">마이페이지</a>\r\n");
      out.write("                            <ul class=\"two--depth\">\r\n");
      out.write("                                <li><a href=");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write(">정보수정</a></li>\r\n");
      out.write("                                <li><a href=\"\">마이리스트</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"header_line\"></div>\r\n");
      out.write("        <main>\r\n");
      out.write("            <section class=\"section1\">\r\n");
      out.write("                <aside>오늘의 추천 앨범\r\n");
      out.write("                    <div class=\"d1\" style=\"overflow: hidden;\">\r\n");
      out.write("                        <!-- Additional required wrapper -->\r\n");
      out.write("                        <div class=\"swiper-wrapper\">\r\n");
      out.write("                            <!-- Slides -->\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/Feeling.png\">Feeling</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/NewJeans.png\">NewJeans 1st EP 'NewJeans'</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/That's Not how This Works.png\">That's Not how\r\n");
      out.write("                                    This Works</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song1.webp\">NewJeans 'Super Shy'</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song3.jpg\">I feel</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song6.jpg\">UNFORGIVEN</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song10.webp\">I've IVE</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song8.webp\">MY WORLD - The 3rd Mini Album</a></div>\r\n");
      out.write("                            <div class=\"swiper-slide\"><a><img src=\"resources/static/img/song4.jpg\">1집 Alone</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </aside>\r\n");
      out.write("                <article>워터멜론에서 즐거운 음악감상하세요!\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <a href=\"\"><img src=\"resources/static/img/user.png\" alt=\"\"></a>\r\n");
      out.write("                        <span>");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("&nbsp;님, 환영합니다!</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h4></h4>\r\n");
      out.write("                    <form method=post action=\"/app/logout\">\r\n");
      out.write("                  	  <button id=\"logout_btn\">LOGOUT</button>\r\n");
      out.write("                  	  </form>\r\n");
      out.write("                </article>\r\n");
      out.write("            </section>\r\n");
      out.write("            <section class=\"section2\">\r\n");
      out.write("                <aside>HOT 수박매거진<br>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"resources/static/img/블랙핑크.png\" width=\"300px\" height=\"220px\" alt=\"\"> BLACKPINK IN COACHELLA <br></a>\r\n");
      out.write("                    <span> 역대 전체 K-POP 아티스트들은 물론, 범위를 넓힌 '아시아계 아티스트'중에서도 코첼라 페스티벌에서 헤드라이너로 선 것은 BLACKPINK 외에는 전례가\r\n");
      out.write("                        없습니다.</span>\r\n");
      out.write("                </aside>\r\n");
      out.write("                <article>멤버십 이벤트<br><br />\r\n");
      out.write("                    <span>워터멜론을 구독해보세요!</span>\r\n");
      out.write("                    <span>첫 구독 1개월 무료</span>\r\n");
      out.write("                    <div><a href=\"\">구독하기</a></div>\r\n");
      out.write("                </article>\r\n");
      out.write("                <aside>\r\n");
      out.write("                    <div class=\"top10\">\r\n");
      out.write("                        <span> WATERMELON </span>\r\n");
      out.write("                        <span> TOP10 </span>\r\n");
      out.write("                        <img src=\"resources/static/img/로고-removebg-preview.png\" alt=\"\">\r\n");
      out.write("                    </div> <br>\r\n");
      out.write("                    <div class=\"table-wrapper\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>No.</th>\r\n");
      out.write("                                <th>TITLE</th>\r\n");
      out.write("                                <th>ARTIST</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">1 -</td>\r\n");
      out.write("                                <td class=\"title\">I AM</td>\r\n");
      out.write("                                <td class=\"artist\">IVE(아이브)</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"id\">2 -</td>\r\n");
      out.write("                                <td class=\"title\">Kitsch</td>\r\n");
      out.write("                                <td class=\"artist\">IVE(아이브)</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"id\">3 -</td>\r\n");
      out.write("                                <td class=\"title\">꽃</td>\r\n");
      out.write("                                <td class=\"artist\">지수(JISOO)</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">4 -</td>\r\n");
      out.write("                                <td class=\"title\">Ditto</td>\r\n");
      out.write("                                <td class=\"artist\">NewJeans</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">5 -</td>\r\n");
      out.write("                                <td class=\"title\">Hype boy</td>\r\n");
      out.write("                                <td class=\"artist\">NewJeans</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">6 -</td>\r\n");
      out.write("                                <td class=\"title\">OMG</td>\r\n");
      out.write("                                <td class=\"artist\">NewJeans</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">7 ▲1</td>\r\n");
      out.write("                                <td class=\"title\">Teddy Bear</td>\r\n");
      out.write("                                <td class=\"artist\">STAYC</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">8 ▼1</td>\r\n");
      out.write("                                <td class=\"title\">사람 pt.2(feat. ...)</td>\r\n");
      out.write("                                <td class=\"artist\">Agust D</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">9 ▲1</td>\r\n");
      out.write("                                <td class=\"title\">Like Crazy</td>\r\n");
      out.write("                                <td class=\"artist\">지민</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"no\">10 -</td>\r\n");
      out.write("                                <td class=\"title\">사랑은 늘 도망가</td>\r\n");
      out.write("                                <td class=\"artist\">임영웅</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <div><a href=\"\">더보기</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </aside>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"footer_line\"></div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <ul class=\"footer_menu\">\r\n");
      out.write("                    <li><a href=\"\">이용약관</a></li>\r\n");
      out.write("                    <li><a href=\"\">고객센터</a></li>\r\n");
      out.write("                    <li><a href=\"\">제휴/프로모션</a></li>\r\n");
      out.write("                    <li><a href=\"\"> 개인정보처리방침</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <div class=\"Site_info\">\r\n");
      out.write("                <img id=\"footer_logo\" src=\"resources/static/img/로고.png\" alt=\"\">\r\n");
      out.write("                <span class=\"Sitename\">(주)WATERMELON MUSIC</span>\r\n");
      out.write("                <span>대구광역시 중구 중앙대로 366 반월센트럴타워 10층</span>\r\n");
      out.write("                <span>대표이사 : 윤치연, 김예솔, 이헌지, 최정기</span>\r\n");
      out.write("                <span>사업자등록번호 : 024-04-02023</span>\r\n");
      out.write("                <br>\r\n");
      out.write("                <span>문의전화 : 1544-1111 (평일 09:00-18:00)</span>\r\n");
      out.write("                <span>WATERMELON MUSIC으로 음악과 함께하는 즐거운 하루 보내세요!</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    const swiper_multi_slider = new Swiper('.section1 .d1', {\r\n");
      out.write("        // Optional parameters\r\n");
      out.write("        direction: 'horizontal',\r\n");
      out.write("        autoplay: { delay: 2000 },\r\n");
      out.write("        loop: true,\r\n");
      out.write("        slidesPerView: 3,\r\n");
      out.write("        loop: true,\r\n");
      out.write("        loopFillGroupWithBlank: true,\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/1.4.0/axios.min.js\" integrity=\"sha512-uMtXmF28A2Ab/JJO2t/vYhlaa/3ahUOgj1Zf27M5rOo8/+fcTUVH0/E0ll68njmjrLqOBjXM3V9NiPFL5ywWPQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("   <!-- <script>\r\n");
      out.write("   	const logout_btn = document.getElementById(\"logout_btn\");\r\n");
      out.write("   	\r\n");
      out.write("   	logout_btn.addEventListener('click', function(){\r\n");
      out.write("   		axios.post(\"/app/logout\")\r\n");
      out.write("   		.then(response =>{\r\n");
      out.write("   			console.log(\"success\")\r\n");
      out.write("   		})\r\n");
      out.write("   		.catch(error=>{console.log(\"error!\");})\r\n");
      out.write("   	})\r\n");
      out.write("   	\r\n");
      out.write("   </script> -->\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/indexlog.jsp(24,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/indexlog");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/indexlog.jsp(25,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/music/search.do");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/indexlog.jsp(29,116) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/music/search.do");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/indexlog.jsp(101,44) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/member/mypage");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/indexlog.jsp(136,30) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.name");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }
}
